### ISSUE TITLE
希望能在登录页面切换账号

### ISSUE THREAD

**Issue by YoungKimKim** [funcenter/See#10]
正在使用的账号主动或被动登出导致跳到登录页面时，如果不登录就无法选择切至其他账号，恢复账号备份也没用。希望能在登录页面加入切换账号功能，谢谢！

**Comment by funcenter** [comment]
暂时可以重启app 会默认切换到第一个账号  这个问题我后续支持一下

**Comment by Caij** [comment]
新版已经添加
