### ISSUE TITLE
折叠平适配严重bug

### ISSUE THREAD

**Issue by shugo-chara** [funcenter/See#12]
mix fold在Android11时see自带的分屏使用正常。

更新到A12 miui13后，无论内外屏see默认都是强制分屏显示，导致外屏拥挤无法正常使用。
且同时see分屏策略不受a12系统策略影响。系统里已经取消分屏显示，但实际see还是内外屏都强制分屏。

外屏截图：让本就窄长的显示更加瘦长😅
![Screenshot_2022-06-04-17-18-00-082-edit_com caij see](https://user-images.githubusercontent.com/20610965/171991355-d6f12cd6-f0e2-4444-bd4a-d6123769617e.jpg)

**Comment by funcenter** [comment]
可以进群试试内测 ， 正式版估计要等一段时间

shugo-chara ***@***.***> 于2022年6月4日周六 16:28写道：
